name: Realise a derivation using Nuenv

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  # Build the Docker image using Nix
  build:
    strategy:
      matrix:
        os: [ubuntu-12, macos-12]
    runs-on: ${{ matrix.os }}
    environment: build
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Build Nuenv derivation
        run: |
          nix build --print-build-logs
          cat result/share/go-help.txt
          cat result/share/go-version.txt

      - name: Build stdenv derivation that depends on Nuenv derivation
        run: |
          nix build --print-build-logs .#other
          cat result/share/version.txt
